# This GitHub action runs Cypress end-to-end tests.
# It includes NPM installation, custom caching and lots of configuration options.
# It will also record videos and store the ones from failures as Artifacts in the repository
name: E2E Tests

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

env: 
  CYPRESS_CACHE_FOLDER: '~/.cache/Cypress'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Cypress with artifacts
    timeout-minutes: 10
    steps:
      # install NPM dependencies, cache them correctly

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.json') }
          restore-keys: |
            cypress-${{ runner.os }}-cypress-

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install


      - name: Run tests with dev server
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above and cypress looks for package-lock.json
          # see https://github.com/cypress-io/github-action/issues/145
          install: false
          start: pnpm dev
          wait-on: 'http://localhost:3001'
          wait-on-timeout: 120
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          # - if the event is push, the title will be undefined and Cypress will get the commit message from Git information
          # - if the event is pull_request, then we set the commit message to the pull request title
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}

      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - name: Upload screenshots on test failures
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - name: Upload videos on test failures
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
