# This GitHub action runs vitest unit tests.
# It includes NPM installation, custom caching and lots of configuration options.
name: Test with Vitest
on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Vitest
    steps:
      # install NPM dependencies, cache them correctly
      - name: Checkout
        uses: actions/checkout@v3
      # run vitest
      - name: Run vitest
        run: npm run vitest run
